# Site
name: "Kristijan Crnac"
title: "Kristijan Crnac"
description: "Kristijan Crnac's blogging platform"
meta_description: "Kristijan Crnac blogging platform"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: ''
email: 'crnac.kristijan@gmail.com'
google_analytics: 'UA-159879067-1'
disqus: 'kcrnac-github-io'
grid_size_post: 6

link:
  github: https://github.com/kcrnac
  linkedin: https://www.linkedin.com/in/kcrnac

include: ["_pages"]

# Authors
authors:
  kcrnac:
    name: Kristijan Crnac
    display_name: kcrnac
    gravatar: 9ebd955d04fcb59383e2668ac4393d60
    email: crnac.kristijan@gmail.com
    web: https://kcrnac.github.io/about
    twitter: https://twitter.com/kcrnac
    description: "Passionate Full-Stack .NET developer who's very motivated, persistent and meticulous with a strong desire for advancement, technology, and learning in general."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
